apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgic-aplicaciones-admin
  namespace: cgic-aplicacionesinternas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgic-admin
  template:
    metadata:
      labels:
        app: cgic-admin
    spec:
      containers:
        - name: cgic-admin
          image: devopsucol/phpmyadmin:cgic-aplicaciones
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: svc-mysql-cgic
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
      
          volumeMounts:
            - name: sessions
              mountPath: /sessions
      volumes:
        - name: sessions
          emptyDir: {}