apiVersion: v1
kind: Service
metadata:
  name: svc-admin-cgic-aplicaciones
  namespace: cgic-aplicacionesinternas
spec:
  type: ClusterIP
  selector:
    app: cgic-admin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
