apiVersion: v1
kind: Service
metadata:
  name: cgic-aplicaciones-svc
  namespace: cgic-aplicacionesinternas
  labels:
    app: cgic-aplicacionesourcecode
spec:
  selector:
   app: cgic-aplicacionesourcecode
  type: ClusterIP
  ports:
   - name: http
     port: 80
     protocol: TCP
     targetPort: 80
  selector:
    role: cgic-aplicacionesourcecode
