apiVersion: v1
kind: Namespace
metadata:
  name: cgic-aplicaciones

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cgic-mysql-pvc
  namespace: cgic-aplicaciones
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
