apiVersion: v1
kind: Namespace
metadata:
  name: cgic-aplicaciones

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cgic-mysql-pvc
  namespace: cgic-aplicaciones
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: cgic-secret
  namespace: cgic-aplicaciones
type: Opaque
data:
  password: NFRjQ0Y=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgic-aplicacion
  namespace: cgic-aplicaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgic-aplicacion
  template:
    metadata:
      labels:
        app: cgic-aplicacion
    spec:
      containers:
        - name: cgic-aplicacion
          image: devopsucol/cgic-aplicaciones:cgic
          env:
            - name: MYSQL_HOST
              value: cgic-mysql-svc
            - name: MYSQL_DATABASE
              value: cgic
            - name: MYSQL_USER
              value: wcgic
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cgic-secret
                  key: password
          ports:
            - containerPort: 3306
              name: cgic-aplicacion
          volumeMounts:
            - name: cgic-mysql-pv
              mountPath: /var/lib/mysql
      volumes:
        - name: cgic-mysql-pv
          persistentVolumeClaim:
            claimName: cgic-mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: cgic-aplicacion
  namespace: cgic-aplicaciones
spec:
  selector:
    app: cgic-aplicacion
  type: ClusterIP
  ports:
  - name: cgic-aplicacion
    port: 3306
    targetPort: 3306
