apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgic-aplicacion
  namespace: cgic-aplicaciones
spec:
  selector:
   matchLabels:
    app: cgic-aplicacion
  replicas: 1
  template:
    metadata:
      labels:
        app: cgic-aplicacion
        role: cgic-aplicacion
    spec:
      containers:
        - name: cgic-aplicacion
          image: devopsucol/cgic-aplicaciones:cgic
          env:
            - name: MYSQL_HOST
              value: localhost
            - name: MYSQL_DATABASE
              value: cgic
            - name: MYSQL_USER
              value: wcgic
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cgic-secret
                  key: password
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: cgic-aplicacion