apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgic-phpmyadmin
  namespace: cgic-aplicaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgic-admin
  template:
    metadata:
      labels:
        app: cgic-admin
    spec:
      containers:
        - name: cgic-admin
          image: devopsucol/cgic-aplicaciones:cgicdb
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: cgic-mysql-svc
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cgic-secret
                  key: DB_PASS
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: sessions
              mountPath: /sessions
      volumes:
        - name: sessions
          emptyDir: {}
