apiVersion: v1
kind: Secret
metadata:
  name: cgic-secret
  namespace: cgic-aplicaciones
type: kubernetes.io/base64
data:
  password: NFRjQ0Y=

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cgic-mysql-pvc
  namespace: cgic-aplicaciones
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgic-phpmyadmin
  namespace: cgic-aplicaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgic-admin
  template:
    metadata:
      labels:
        app: cgic-admin
    spec:
      containers:
        - name: cgic-admin
          image: devopsucol/cgic-aplicaciones:cgicdb
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: cgic-mysql-svc
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cgic-secret
                  key: password
            - name: MAX_EXECUTION_TIME
              value: "5000"
            - name: MEMORY_LIMIT
              value: "10000K"
            - name: UPLOAD_LIMIT
              value: "10000K"
          volumeMounts:
            - name: sessions
              mountPath: /sessions
      volumes:
        - name: sessions
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: cgic-admin-svc
  namespace: cgic-aplicaciones
spec:
  type: ClusterIP
  selector:
    app: cgic-admin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
