apiVersion: v1
kind: Secret
metadata:
  name: cgic-secret
  namespace: cgic-aplicaciones
type: Opaque
data:
  root-password: NFRjQ0Y=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgic-phpmyadmin
  namespace: cgic-aplicaciones
  labels:
    app: cgic-phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgic-phpmyadmin
  template:
    metadata:
      labels:
        app: cgic-phpmyadmin
    spec:
      containers:
        - name: cgic-admin
          image: devopsucol/cgic-aplicaciones:cgicdb
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: cgic-mysql-svc
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cgic-secret
                  key: root-password
            - name: MAX_EXECUTION_TIME
              value: "5000"
            - name: MEMORY_LIMIT
              value: "10000K"
            - name: UPLOAD_LIMIT
              value: "10000K"

---
apiVersion: v1
kind: Service
metadata:
  name: cgic-admin-svc
  namespace: cgic-aplicaciones
spec:
  type: LoadBalancer
  loadBalancerIP: 148.213.1.148
  selector:
    app: cgic-phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

