apiVersion: v1
kind: Service
metadata:
  name: cgic-admin-svc
  namespace: cgic-aplicaciones
spec:
  type: ClusterIP
  selector:
    app: cgic-admin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80