apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgic-aplicaciones-deploy
  namespace: cgic-aplicacionesinternas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgic-mysql
  template:
    metadata:
      labels:
        app: cgic-mysql
    spec:
      containers:
        - name: cgic-mysql
          image: mysql:5.1.41
          imagePullPolicy: Always
          env:
            - name: MYSQL_PASSWORD  
              valueFrom:
                secretKeyRef:
                  name: cgic-secret-mysql
                  key: password
          ports:
            - containerPort: 3306
              name: cgic-mysql
          
          volumeMounts:
            - name: mysql-data-cgic
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-data-cgic
          persistentVolumeClaim:
            claimName: cgic-data-disk