apiVersion: v1
kind: Service
metadata:
  name: cgic-aplicaciones-svc
  namespace: cgic-aplicacionesinternas
spec:
  selector:
    app: cgic-mysql
  type: ClusterIP
  ports:
    - name: cgic-mysql
      port: 3306
      targetPort: 3306