apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cgic-data-disk
  namespace: cgic-aplicacionesinternas
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
