apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-dj
  namespace: cgic-aplicaciones
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

  