apiVersion: batch/v1
kind: Job
metadata:
  name: import-db
spec:
  template:
    spec:
      containers:
        - name: mysql
          image: mysql:5.6.51
          command: ["mysql"]
          args: ["-h", "cgic-mysql-svc", "-u", "wcgic", "-p", "cgic", "<", "/home/digesetuser/cgic-aplicaciones/cgic.sql"]
          env:
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: cgic-secret
                  key: DB_PASS
          volumeMounts:
            - name: sql-file
              mountPath: /home/digesetuser/cgic-aplicaciones/cgic.sql
      restartPolicy: Never
      volumes:
        - name: sql-file
          hostPath:
            path: /home/digesetuser/cgic-aplicaciones/cgic.sql
