apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgic-mysql
  namespace: cgic-aplicaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgic-mysql
  template:
    metadata:
      labels:
        app: cgic-mysql
    spec:
      containers:
        - name: cgic-mysql
          image: mysql:5.5.62
          env:
            - name: DB_HOST
              value: localhost
            - name: MYSQL_USER
              value: wcgic
            - name: MYSQL_DATABASE
              value: cgic
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cgic-secret
                  key: password
          ports:
            - containerPort: 3306
              name: cgic-mysql
          volumeMounts:
            - name: cgic-mysql-pv
              mountPath: /var/lib/mysql
      volumes:
        - name: cgic-mysql-pv
          persistentVolumeClaim:
            claimName: cgic-mysql-pvc


