apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cgic-mysql-data-disk
  namespace: cgic-aplicaciones
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  