apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgic-mysql
  namespace: cgic-aplicaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgic-mysql
  template:
    metadata:
      labels:
        app: cgic-mysql
    spec:
      containers:
        - name: cgic-mysql
          image: mysql:5.6.51
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - exec mysql -uroot -p4TcCF --init-command="SET SESSION FOREIGN_KEY_CHECKS=0" < /docker-entrypoint-initdb.d/cgic.sql
          env:
            - name: DB_HOST
              value: localhost
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_DATABASE
              value: cgic
            - name: MYSQL_USER
              value: wcgic
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cgic-secret
                  key: DB_PASS
          ports:
            - containerPort: 3306
              name: cgic-mysql
          volumeMounts:
            - name: cgic-mysql-data
              mountPath: /docker-entrypoint-initdb.d/cgic.sql
              subPath: cgic.sql
      volumes:
        - name: cgic-mysql-data
          hostPath:
            path: /home/digesetuser/cgic-aplicaciones











