apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgic-mysql
  namespace: cgic-aplicaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgic-mysql
  template:
    metadata:
      labels:
        app: cgic-mysql
    spec:
      containers:
        - name: cgic-mysql
          image: mysql:5.5
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cgic-secret
                  key: password
          ports:
            - containerPort: 3306
              name: cgic-mysql
          volumeMounts:
            - name: cgic-mysql-pv
              mountPath: /var/lib/mysql
            - name: cgic-sql-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: cgic-mysql-pv
          persistentVolumeClaim:
            claimName: cgic-mysql-pvc
        - name: cgic-sql-scripts
          configMap:
            name: import-sql-scripts1


