apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgic-mysql
  namespace: cgic-aplicaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgic-mysql
  template:
    metadata:
      labels:
        app: cgic-mysql
    spec:
      containers:
        - name: cgic-mysql
          image: mysql:5.7.25
          command: ["sh", "-c", "mysql -h localhost -P 3306 -u wcgic -p4TcCF cgic < /home/digesetuser/cgic.sql"]
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: localhost
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_DATABASE
              value: cgic
            - name: MYSQL_USER
              value: wcgic
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cgic-secret
                  key: DB_PASS
          ports:
            - containerPort: 3306
              name: cgic-mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
          











