apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cgic-mysql-pvc
  namespace: cgic-aplicaciones
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: cgic-secret
  namespace: cgic-aplicaciones
type: kubernetes.io/base64
data:
  rootpassword: NFRjQ0Y=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgic-mysql
  namespace: cgic-aplicaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.5
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cgic-secret
                  key: rootpassword
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: cgic-mysql-pv
              mountPath: /var/lib/mysql
            - name: cgic-sql-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: cgic-mysql-pv
          persistentVolumeClaim:
            claimName: cgic-mysql-pvc
        - name: cgic-sql-scripts
          configMap:
            name: import-sql-scripts1
---
apiVersion: v1
kind: Service
metadata:
  name: cgic-mysql-svc
  namespace: cgic-aplicaciones
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306

