apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgic-mysql
  namespace: cgic-aplicaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgic-mysql
  template:
    metadata:
      labels:
        app: cgic-mysql
    spec:
      containers:
        - name: cgic-mysql
          image: mysql:5.5.62
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
          ports:
            - containerPort: 3306
              name: cgic-mysql-pvc
          volumeMounts:
            - name: cgic-mysql-pvc
              mountPath: /var/lib/mysql
            - name: import-sql-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: cgic-mysql-pvc
          persistentVolumeClaim:
            claimName: cgic-mysql-pvc
        - name: import-sql-scripts
          configMap:
            name: import-sql-scripts


