apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: cgic-aplicaciones
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/mysql
