apiVersion: v1
kind: Namespace
metadata:
  name: cgic-aplicaciones
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgic-phpmyadmin
  namespace: cgic-aplicaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgic-admin
  template:
    metadata:
      labels:
        app: cgic-admin
    spec:
      containers:
        - name: cgic-admin
          image: devopsucol/cgic-aplicaciones:cgicdb
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: cgic-mysql-svc
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: cgic-secret
                  key: password
          volumeMounts:
            - name: sessions
              mountPath: /sessions
      volumes:
        - name: sessions
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cgic-admin-svc
  namespace: cgic-aplicaciones
spec:
  type: ClusterIP
  selector:
    app: cgic-admin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80