apiVersion: v1
kind: Namespace
metadata:
  name: cgic-aplicaciones
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cgic-mysql-data-disk
  namespace: cgic-aplicaciones
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: cgic-secret
  namespace: cgic-aplicaciones
type: kubernetes.io/base64
data:
  DB_PASS: NFRjQ0Y=
  DB_USER_PASSWORD: NFRjQ0Y=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgic-mysql
  namespace: cgic-aplicaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgic-mysql
  template:
    metadata:
      labels:
        app: cgic-mysql
    spec:
      containers:
        - name: cgic-mysql
          image: mysql:5.7
          env:
            - name: DB_HOST
              value: ww.ucol.mx
            - name: DB_USER
              value: wcgic
            - name: DB_NAME
              value: cgic.sql
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cgic-secret
                  key: DB_PASS
          ports:
            - containerPort: 3306
              name: cgic-mysql
          volumeMounts:
            - name: cgic-mysql-data
              mountPath: /var/lib/mysql
          command: ["/bin/sh", "-c", "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'CREATE USER \"$DB_USER\" IDENTIFIED BY \"$DB_USER_PASSWORD\";'"]
      volumes:
        - name: cgic-mysql-data
          persistentVolumeClaim:
            claimName: cgic-mysql-data-disk
 
---
apiVersion: v1
kind: Service
metadata:
  name: cgic-mysql-svc
  namespace: cgic-aplicaciones
spec:
  selector:
    app: cgic-mysql
  type: ClusterIP
  ports:
    - name: cgic-mysql
      port: 3306
      targetPort: 3306