apiVersion: v1
kind: Namespace
metadata:
  name: cgic-aplicaciones

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgic-aplicacion
  namespace: cgic-aplicaciones
spec:
  selector:
   matchLabels:
    app: cgic-aplicacion
  replicas: 1
  template:
    metadata:
      labels:
        app: cgic-aplicacion
        role: cgic-aplicacion
    spec:
      containers:
        - name: cgic-aplicacion
          image: devopsucol/cgic-aplicaciones:cgic
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: cgic-aplicacion

---
apiVersion: v1
kind: Service
metadata:
  name: cgic-aplicacion
  namespace: cgic-aplicaciones
  labels:
    app: cgic-aplicacion
spec:
  selector:
   app: cgic-aplicacion
  type: ExternalName
  externalName: nginx-internal.service-ns.svc.cluster.local
  type: ClusterIP
  ports:
   - name: http
     port: 80
     protocol: TCP
     targetPort: 80
  selector:
    role: cgic-aplicacion

