apiVersion: v1
kind: Namespace
metadata:
  name: cgic-aplicaciones
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-cgic
  namespace: cgic-aplicaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-cgic
  template:
    metadata:
      labels:
        app: phpmyadmin-cgic
    spec:
      containers:
        - name: phpmyadmin-cgic
          image: devopsucol/phpmyadmin:cgic
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: cgic-mysql-svc
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-cgic
                  key: password
      
          volumeMounts:
            - name: sessions
              mountPath: /sessions
      volumes:
        - name: sessions
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: cgic-aplicaciones
spec:
  type: ClusterIP
  selector:
    app: phpmyadmin-cgic
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
