apiVersion: v1
kind: Namespace
metadata:
  name: cgic-aplicaciones
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-disk
  namespace: cgic-aplicaciones
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: cgic-aplicaciones
type: Opaque
data:
  password: NFRjQ0Y=
  host: ww.ucol.mx
  user: wcgic
  dbname: cgic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgic-mysql-deploy
  namespace: cgic-aplicaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-cgic
  template:
    metadata:
      labels:
        app: mysql-cgic
    spec:
      containers:
            - name: DB_HOST
              value: host
            - name: DB_USER
              value: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: dbname
          ports:
            - containerPort: 3306
              name: mysql-cgic
          volumeMounts:
            - name: mysql-data-cgic
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data-cgic
          persistentVolumeClaim:
            claimName: mysql-data-disk
---
apiVersion: v1
kind: Service
metadata:
  name: cgic-mysql-service
  namespace: cgic-aplicaciones
spec:
  selector:
    app: mysql-cgic
  type: ClusterIP
  ports:
    - name: mysql-cgic
      port: 3306
      targetPort: 3306