apiVersion: v1
kind: Namespace
metadata:
  name: cgic-aplicaciones

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgic-mysql
  namespace: cgic-aplicaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgic-mysql
  template:
    metadata:
      labels:
        app: cgic-mysql
    spec:
      containers:
        - name: cgic-mysql
          image: mysql:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_PASSWORD  
              valueFrom:
                secretKeyRef:
                  name: secret-cgic
                  key: password
          ports:
            - containerPort: 3306
              name: cgic-mysql
          
          volumeMounts:
            - name: mysql-cgic-data
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-cgic-data
          persistentVolumeClaim:
            claimName: mysql-data-disk-cgic

---
apiVersion: v1
kind: Service
metadata:
  name: cgic-mysql-svc
  namespace: cgic-aplicaciones
spec:
  selector:
    app: cgic-mysql
  type: ClusterIP
  ports:
    - name: cgic-mysql
      port: 3306
      targetPort: 3306
