apiVersion: v1
kind: Namespace
metadata:
  name: cgic-aplicaciones
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cgic-volumen
  namespace: cgic-aplicaciones
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-cgic
  namespace: cgic-aplicaciones
type: Opaque
data:
  password: Y2dpYy1hcGxpY2FjaW9uZXM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgic-mysql
  namespace: cgic-aplicaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgic-mysql
  template:
    metadata:
      labels:
        app: cgic-mysql
    spec:
      containers:
        - name: cgic-mysql
          image: mysql:latest
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-cgic
                  key: password
          ports:
            - containerPort: 3306
              name: cgic-mysql
          volumeMounts:
            - name: volumen-mysql
              mountPath: /var/lib/mysql
      volumes:
        - name: volumen-mysql
          persistentVolumeClaim:
            claimName: cgic-volumen
---
apiVersion: v1
kind: Service
metadata:
  name: cgic-mysql-svc
  namespace: cgic-aplicaciones
spec:
  selector:
    app: cgic-mysql
  type: ClusterIP
  ports:
    - name: cgic-mysql
      port: 3306
      targetPort: 3306